default:
  tags:
    - apap

.setup-ssh:
  before_script:
  - curl -fsSL https://railway.app/install.sh | sh


stages:
  - build
  - deploy


variables:
  IMAGE_OPENJDK_GRADLE: gradle:8.11.1-jdk21-alpine

# Separate build jobs
# Build Jobs
build-profile:
  image: $IMAGE_OPENJDK_GRADLE
  stage: build
  script:
    - echo "Building profile service..."
    - cd $CI_PROJECT_DIR/profile
    - sh gradlew clean assemble
  artifacts:
    paths:
      - profile/build/libs/profile-0.0.1-SNAPSHOT.jar

build-purchase:
  image: $IMAGE_OPENJDK_GRADLE
  stage: build
  script:
    - echo "Building purchase service..."
    - cd $CI_PROJECT_DIR/purchase
    - sh gradlew clean assemble
  artifacts:
    paths:
      - purchase/build/libs/purchase-0.0.1-SNAPSHOT.jar

build-asset:
  image: $IMAGE_OPENJDK_GRADLE
  stage: build
  script:
    - echo "Building asset service..."
    - cd $CI_PROJECT_DIR/asset
    - sh gradlew clean assemble
  artifacts:
    paths:
      - asset/build/libs/asset-0.0.1-SNAPSHOT.jar

build-finance:
  image: $IMAGE_OPENJDK_GRADLE
  stage: build
  script:
    - echo "Building finance service..."
    - cd $CI_PROJECT_DIR/finance
    - sh gradlew clean assemble
  artifacts:
    paths:
      - finance/build/libs/finance-0.0.1-SNAPSHOT.jar

build-project:
  image: $IMAGE_OPENJDK_GRADLE
  stage: build
  script:
    - echo "Building project service..."
    - cd $CI_PROJECT_DIR/project
    - sh gradlew clean assemble
  artifacts:
    paths:
      - project/build/libs/project-0.0.1-SNAPSHOT.jar


# Deploy Jobs
deploy-asset:
  stage: deploy
  script:
    - echo "Deploying asset service to Railway..."
    - railway login --token $RAILWAY_TOKEN
    - railway up --service asset

deploy-finance:
  stage: deploy
  script:
    - echo "Deploying finance service to Railway..."
    - railway login --token $RAILWAY_TOKEN
    - railway up --service finance

deploy-profile:
  stage: deploy
  script:
    - echo "Deploying profile service to Railway..."
    - railway login --token $RAILWAY_TOKEN
    - railway up --service profile


deploy-project:
  stage: deploy
  script:
    - echo "Deploying project service to Railway..."
    - railway login --token $RAILWAY_TOKEN
    - railway up --service project

deploy-resource:
  stage: deploy
  script:
    - echo "Deploying resource service to Railway..."
    - railway login --token $RAILWAY_TOKEN
    - railway up --service resource

deploy-purchase:
  stage: deploy
  script:
    - echo "Deploying purchase service to Railway..."
    - railway login --token $RAILWAY_TOKEN
    - railway up --service purchase