stages:
  - build
  - deploy

variables:
  IMAGE_OPENJDK_GRADLE: gradle:8.11.1-jdk21-alpine
  UBUNTU: ubuntu:latest

# Build Jobs
build:
  image: $IMAGE_OPENJDK_GRADLE
  stage: build
  parallel:
    matrix:
      - SERVICE: ["profile"]
  script:
    - echo "Building $SERVICE service..."
    - cd $CI_PROJECT_DIR/$SERVICE
    - sh gradlew clean assemble
  artifacts:
    paths:
      - $CI_PROJECT_DIR/$SERVICE/build/libs/*.jar

# Deploy Jobs
deploy:
  image: $UBUNTU
  stage: deploy
  variables:
    RAILWAY_API_TOKEN: $YOUR_RAILWAY_API_TOKEN
  parallel:
    matrix:
      - SERVICE: ["profile"]
  script:
    - echo "Deploying $SERVICE to Railway..."
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | sh
    - railway link --environment Development --project $RAILWAY_PROJECT_ID
    - echo "Testing Railway Authentication..."
    - railway whoami
    - railway up --service $SERVICE
  only:
    - railway-deploy
