version: "3.8"

services:
  asset:
    image: gcr.io/propensi-451504/asset:latest
    container_name: asset_service
    restart: always
    ports:
      - "8080:8080"
    

  dashboard:
    image: gcr.io/propensi-451504/dashboard:latest
    container_name: dashboard_service
    restart: always
    ports:
      - "8081:8081"
    

  finance:
    image: gcr.io/propensi-451504/finance:latest
    container_name: finance_service
    restart: always
    ports:
      - "8082:8082"
    

  profile:
    image: gcr.io/propensi-451504/profile:latest
    container_name: profile_service
    restart: always
    ports:
      - "8083:8083"
    

  project:
    image: gcr.io/propensi-451504/project:latest
    container_name: project_service
    restart: always
    ports:
      - "8084:8084"
    

  purchase:
    image: gcr.io/propensi-451504/purchase:latest
    container_name: purchase_service
    restart: always
    ports:
      - "8085:8085"
    

  resource:
    image: gcr.io/propensi-451504/resource:latest
    container_name: resource_service
    restart: always
    ports:
      - "8086:8086"

networks:
  default:
    driver: bridge
