server:
  port: 8084
spring:
  application:
    name: purchase
  datasource:
    url: ${DATABASE_URL_PURCHASE}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
  config:
    import: optional:file:.env[.properties]
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
purchase:
  app:
    jwtPublicKey: ${JWT_PUBLIC_KEY}
    jwtExpirationMs: ${JWT_EXPIRATION_MS}
    assetUrl: ${ASSET_URL}
    profileUrl: ${PROFILE_URL}
    financeUrl: ${FINANCE_URL}
    projectUrl: ${PROJECT_URL}
    purchaseUrl: ${PURCHASE_URL}
    resourceUrl: ${RESOURCE_URL}
    frontendUrl: ${FRONTEND_URL}
file:
  upload-dir: purchase-images
logging:
  file:
    name: logs/purchase-application.log
  level:
    root: INFO
    gpl.karina.purchase: DEBUG
