server:
    port: 8084
spring:
  application:
    name: purchase
  datasource:
    url: ${DATABASE_URL_DEV}
    username: ${DATABASE_USERNAME_DEV}
    password: ${DATABASE_PASSWORD_DEV}
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
  config:
    import: optional:file:.env[.properties]
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
purchase:
  app:
    jwtSecret: ${JWT_SECRET_KEY}
    jwtExpirationMs: 86400000
