server:
    port: 8082
spring:
  application:
    name: finance.report
  datasource:
    url: ${DATABASE_URL_DEV}
    username: ${DATABASE_USERNAME_DEV}
    password: ${DATABASE_PASSWORD_DEV}
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
  config:
    import: optional:file:.env[.properties]
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
finance.report:
  app:
    jwtPublicKey: ${JWT_PUBLIC_KEY}
    jwtExpirationMs: ${JWT_EXPIRATION_MS}


logging:
  file:
    name: logs/finance-report-application.log
  level:
    root: INFO
    gpl.karina.finance.report: DEBUG
