spring:
  application:
    name: asset
  datasource:
    url: postgresql://postgres:UuMOCgOOamDlBVItyiJkDnSXFaLlzPeR@hopper.proxy.rlwy.net:55694/railway
    username: postgres
    password: UuMOCgOOamDlBVItyiJkDnSXFaLlzPeR
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
  config:
    import: optional:file:.env[.properties]
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
asset:
  app:
    jwtSecret: ${JWT_SECRET_KEY:HWlEIJMvCDcKFNTzNOXCVjrArVFkLbcEa}
    jwtExpirationMs: 86400000
