server:
    port: 8081
spring:
  application:
    name: asset
  datasource:
    url: ${DATABASE_URL_ASSET}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
  config:
    import: optional:file:.env[.properties]
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
asset:
  app:
    jwtPublicKey: ${JWT_PUBLIC_KEY}
    jwtExpirationMs: ${JWT_EXPIRATION_MS}
    profileUrl: ${PROFILE_URL}
    financeUrl: ${FINANCE_URL}
    projectUrl: ${PROJECT_URL}
    purchaseUrl: ${PURCHASE_URL}
    resourceUrl: ${RESOURCE_URL}
logging:
  file:
    name: logs/asset-application.log
  level:
    root: INFO
    gpl.karina.asset: DEBUG